use std::{
    env, fs,
    path::{Path, PathBuf},
};

#[path = "src/cleanup/rules/declarative_schema.rs"]
#[allow(dead_code)]
mod declarative_schema;
#[path = "src/cleanup/cleaners/project_artifact_schema.rs"]
#[allow(dead_code)]
mod project_artifact_schema;
#[path = "src/cleanup/rules/protected_paths.rs"]
#[allow(dead_code)]
mod protected_paths;

#[path = "src/ai/prompt_schema.rs"]
mod prompt_schema;

fn main() {
    println!("cargo:rerun-if-changed=src/ai/prompts");
    prompt_schema::load()
        .unwrap_or_else(|error| panic!("AI prompt build validation failed: {error}"));
    let manifest_directory = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo must provide a manifest directory"),
    );
    let rules_directory = manifest_directory.join("rules");
    let filesystem_rules_directory = rules_directory.join("filesystem");
    let project_rules_directory = rules_directory.join("project-artifacts");
    println!("cargo:rerun-if-changed={}", rules_directory.display());

    let owned_sources = load_rule_sources(&filesystem_rules_directory, "filesystem cleanup")
        .unwrap_or_else(|error| panic!("failed to load filesystem cleanup rules: {error}"));
    let source_references = owned_sources
        .iter()
        .map(|(name, content)| (name.as_str(), content.as_str()))
        .collect::<Vec<_>>();
    declarative_schema::parse_catalog(&source_references)
        .unwrap_or_else(|error| panic!("declarative rule build validation failed: {error}"));
    write_embedded_sources(
        "embedded-cleanup-rules.rs",
        "EMBEDDED_DECLARATIVE_RULE_SOURCES",
        &owned_sources,
    )
    .unwrap_or_else(|error| panic!("failed to embed filesystem cleanup rules: {error}"));

    let project_sources = load_rule_sources(&project_rules_directory, "project artifact")
        .unwrap_or_else(|error| panic!("failed to load project artifact rules: {error}"));
    let project_references = project_sources
        .iter()
        .map(|(name, content)| (name.as_str(), content.as_str()))
        .collect::<Vec<_>>();
    project_artifact_schema::parse_catalog(&project_references)
        .unwrap_or_else(|error| panic!("project artifact rule build validation failed: {error}"));
    write_embedded_sources(
        "embedded-project-artifact-rules.rs",
        "EMBEDDED_PROJECT_ARTIFACT_RULE_SOURCES",
        &project_sources,
    )
    .unwrap_or_else(|error| panic!("failed to embed project artifact rules: {error}"));
}

fn load_rule_sources(
    directory: &Path,
    catalog_name: &str,
) -> Result<Vec<(String, String)>, String> {
    let mut files = Vec::new();
    collect_rule_files(directory, &mut files)?;
    files.sort();
    if files.is_empty() {
        return Err(format!(
            "the {catalog_name} rule directory must contain at least one TOML file"
        ));
    }

    files
        .into_iter()
        .map(|path| {
            let source_name = path
                .strip_prefix(directory)
                .map_err(|error| format!("{}: {error}", path.display()))?
                .to_string_lossy()
                .replace('\\', "/");
            let content = fs::read_to_string(&path)
                .map_err(|error| format!("{}: {error}", path.display()))?;
            Ok((source_name, content))
        })
        .collect()
}

fn write_embedded_sources(
    output_name: &str,
    constant_name: &str,
    sources: &[(String, String)],
) -> Result<(), String> {
    let mut generated = format!(
        "// Generated by mangodisk-core/build.rs. Do not edit manually.\n\
         pub(super) const {constant_name}: &[(&str, &str)] = &[\n"
    );
    for (source_name, content) in sources {
        generated.push_str(&format!("    ({source_name:?}, {content:?}),\n"));
    }
    generated.push_str("];\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo must provide OUT_DIR"))
        .join(output_name);
    fs::write(&output, generated).map_err(|error| format!("{}: {error}", output.display()))
}

fn collect_rule_files(directory: &Path, output: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in
        fs::read_dir(directory).map_err(|error| format!("{}: {error}", directory.display()))?
    {
        let entry = entry.map_err(|error| format!("{}: {error}", directory.display()))?;
        let file_type = entry
            .file_type()
            .map_err(|error| format!("{}: {error}", entry.path().display()))?;
        if file_type.is_symlink() {
            return Err(format!(
                "the rule directory must not contain symbolic links: {}",
                entry.path().display()
            ));
        }
        if file_type.is_dir() {
            collect_rule_files(&entry.path(), output)?;
        } else if file_type.is_file()
            // Finder and some macOS archive tools create AppleDouble sidecars
            // whose names end in `.toml`. They contain binary metadata rather
            // than rule sources and must not make a Windows source copy fail.
            && !entry.file_name().to_string_lossy().starts_with("._")
            && entry
                .path()
                .extension()
                .is_some_and(|value| value == "toml")
        {
            output.push(entry.path());
        }
    }
    Ok(())
}
