import { CLEANUP_RULE_IDS, type CleanupResultGroup } from '@/lib/models/cleanup';
import { ICON_NAMES, type IconName } from '@/lib/models/ui';

const CLEANUP_GROUP_ICONS: Readonly<Record<CleanupResultGroup, IconName>> = {
  custom: ICON_NAMES.folderPlus,
  system: ICON_NAMES.cleanupSystemCache,
  userCache: ICON_NAMES.cleanupUserCache,
  application: ICON_NAMES.cleanupApplicationCache,
  browser: ICON_NAMES.cleanupBrowserData,
  development: ICON_NAMES.cleanupDeveloperTools,
  project: ICON_NAMES.cleanupProjectArtifacts,
  xcode: ICON_NAMES.brandXcode,
  applicationOptimization: ICON_NAMES.cleanupApplicationOptimization,
  ai: ICON_NAMES.cleanupAiModelCache,
  container: ICON_NAMES.brandDocker,
};

// Rule IDs are stable protocol values, so brand selection remains independent
// from localized labels and private filesystem paths. Unknown rules deliberately
// fall back to their domain icon instead of guessing a visually similar brand.
const CLEANUP_RULE_ICONS: Readonly<Record<string, IconName>> = {
  'system.user-temp': ICON_NAMES.cleanupTemporaryFiles,
  'system.darwin-user-cache': ICON_NAMES.cleanupStaleCache,
  'system.old-diagnostic-logs': ICON_NAMES.cleanupDiagnosticLogs,
  'system.crash-dumps': ICON_NAMES.cleanupCrashReports,
  'system.error-reports': ICON_NAMES.cleanupCrashReports,
  'system.geo-services-cache': ICON_NAMES.cleanupLocationCache,
  'system.help-cache': ICON_NAMES.help,
  'system.parsecd-cache': ICON_NAMES.search,
  'system.quicklook-cache': ICON_NAMES.cleanupPreviewCache,
  'system.stale-partial-downloads': ICON_NAMES.download,
  'system.thumbnail-cache': ICON_NAMES.fileImage,
  'system.apple-media-cache': ICON_NAMES.brandApple,
  'system.apple-intelligence-cache': ICON_NAMES.brandApple,
  'system.aerial-video-downloads': ICON_NAMES.wallpaper,
  'system.ios-firmware-downloads': ICON_NAMES.brandApple,
  'system.directx-shader-cache': ICON_NAMES.brandWindows,
  'system.dns-cache': ICON_NAMES.network,
  'system.font-cache': ICON_NAMES.fileText,
  'system.gtk-icon-cache': ICON_NAMES.fileImage,
  [CLEANUP_RULE_IDS.windowsRecycleBin]: ICON_NAMES.trash,
  'special.windows-system-logs': ICON_NAMES.brandWindows,
  'special.windows-internet-cache': ICON_NAMES.brandWindows,
  'special.windows-delivery-optimization': ICON_NAMES.brandWindows,
  'special.windows-defender-cache': ICON_NAMES.brandWindows,
  'special.windows-update-cleanup': ICON_NAMES.brandWindows,
  [CLEANUP_RULE_IDS.windowsPreviousInstallations]: ICON_NAMES.brandWindows,

  'app.slack-cache': ICON_NAMES.brandSlack,
  'app.claude-cache': ICON_NAMES.brandClaude,
  'app.discord-cache': ICON_NAMES.brandDiscord,
  'app.zoom-cache': ICON_NAMES.brandZoom,
  'app.teams-cache': ICON_NAMES.brandTeams,
  'app.teams-msix-cache': ICON_NAMES.brandTeams,
  'app.chatgpt-cache': ICON_NAMES.brandOpenai,
  'app.ollama-update-cache': ICON_NAMES.brandOllama,
  'app.parallels-windows-image-cache': ICON_NAMES.brandWindows,
  'app.ynote-cache': ICON_NAMES.brandYoudaoNote,
  'app.flashvoice-cache': ICON_NAMES.fileAudio,
  'app.baidu-netdisk-rendering-cache': ICON_NAMES.brandBaiduNetdisk,
  'app.manus-rendering-cache': ICON_NAMES.brandManus,
  'app.manus-update-cache': ICON_NAMES.brandManus,
  'app.workbuddy-rendering-cache': ICON_NAMES.brandWorkBuddy,
  'app.clash-verge-diagnostic-cache': ICON_NAMES.network,
  'app.youdao-translation-cache': ICON_NAMES.languages,
  'app.gitmind-rendering-cache': ICON_NAMES.brandGitMind,
  'app.whatsapp-rendering-cache': ICON_NAMES.brandWhatsapp,
  'app.electron-updater-cache': ICON_NAMES.brandElectron,
  'app.lobsterai-update-cache': ICON_NAMES.brandLobsterAi,
  'app.zenaion-cache': ICON_NAMES.aiTools,
  'app.xmind-rendering-cache': ICON_NAMES.brandXmind,
  'app.tencent-lemon-cache': ICON_NAMES.cleanupApplicationOptimization,
  'app.thunder-cache': ICON_NAMES.brandXunlei,
  'app.sogou-input-cache': ICON_NAMES.brandSogou,
  'app.signal-cache': ICON_NAMES.brandSignal,
  'app.postman-cache': ICON_NAMES.brandPostman,
  'app.netease-cloud-music-cache': ICON_NAMES.brandNeteaseMusic,
  'app.telegram-temporary-cache': ICON_NAMES.brandTelegram,
  'app.vlc-cache': ICON_NAMES.brandVlc,
  'app.ea-rendering-cache': ICON_NAMES.brandEa,
  'app.steam-rendering-cache': ICON_NAMES.brandSteam,
  'app.battlenet-cache': ICON_NAMES.brandBattleNet,
  'app.spotify-rendering-cache': ICON_NAMES.brandSpotify,
  'app.douyin-live-updater-cache': ICON_NAMES.video,
  'app.dropbox-rendering-cache': ICON_NAMES.brandDropbox,
  'app.electron-cache': ICON_NAMES.brandElectron,
  'app.electron-productivity-cache': ICON_NAMES.brandElectron,
  'app.figma-cache': ICON_NAMES.brandFigma,
  'app.game-launcher-cache': ICON_NAMES.game,
  'app.lm-studio-cache': ICON_NAMES.brandLmStudio,
  'app.media-analysis-cache': ICON_NAMES.video,
  'app.media-cache': ICON_NAMES.video,
  'app.notion-cache': ICON_NAMES.brandNotion,
  'app.notion-service-worker-cache': ICON_NAMES.brandNotion,
  'app.iqiyi-rendering-cache': ICON_NAMES.brandIqiyi,
  'app.qqlive-rendering-cache': ICON_NAMES.brandTencentVideo,
  'app.qqlive-update-cache': ICON_NAMES.brandTencentVideo,
  'app.youku-rendering-cache': ICON_NAMES.brandYouku,
  'app.obs-diagnostic-cache': ICON_NAMES.brandObs,
  'app.adobe-media-cache': ICON_NAMES.brandAdobe,
  'app.office-cache': ICON_NAMES.brandOffice,
  'app.outlook-cache': ICON_NAMES.brandOffice,
  'app.apple-mail-cache': ICON_NAMES.brandApple,
  'app.iwork-cache': ICON_NAMES.brandApple,
  'app.core-device-cache': ICON_NAMES.brandApple,
  'app.google-updater-cache': ICON_NAMES.brandGoogle,
  'app.wechat-cache': ICON_NAMES.brandWechat,
  'app.wechat-rendering-cache': ICON_NAMES.brandWechat,
  'app.wecom-cache': ICON_NAMES.brandWechat,
  'app.wecom-diagnostic-cache': ICON_NAMES.brandWechat,
  'app.wechat-diagnostic-cache': ICON_NAMES.brandWechat,
  'app.dingtalk-content-cache': ICON_NAMES.brandDingtalk,
  'app.dingtalk-diagnostic-cache': ICON_NAMES.brandDingtalk,
  'app.telegram-cache': ICON_NAMES.brandTelegram,
  'app.tencent-meeting-cache': ICON_NAMES.brandTencentMeeting,
  'app.thunderbird-cache': ICON_NAMES.brandThunderbird,
  'app.whatsapp-cache': ICON_NAMES.brandWhatsapp,
  'app.wallpaper-agent-cache': ICON_NAMES.wallpaper,
  'app.wps-cache': ICON_NAMES.brandWps,
  'app.wps-rendering-cache': ICON_NAMES.brandWps,
  'app.wps-diagnostic-cache': ICON_NAMES.brandWps,
  'app.qq-cache': ICON_NAMES.brandQq,
  'app.qq-update-cache': ICON_NAMES.brandQq,
  'app.qq-rendering-cache': ICON_NAMES.brandQq,
  'app.qwenwork-cache': ICON_NAMES.brandQwenWork,
  'app.utools-rendering-cache': ICON_NAMES.brandUtools,
  'app.zoom-diagnostic-cache': ICON_NAMES.brandZoom,
  'app.lark-renderer-cache': ICON_NAMES.brandLark,
  'app.blender-cache': ICON_NAMES.brandBlender,
  'app.cargo-cache': ICON_NAMES.brandRust,
  'app.chrome-cache': ICON_NAMES.brandChrome,
  'app.docker-build-cache': ICON_NAMES.brandDocker,
  'app.firefox-cache': ICON_NAMES.brandFirefox,
  'app.gimp-cache': ICON_NAMES.brandGimp,
  'app.gradle-cache': ICON_NAMES.brandGradle,
  'app.gtk-doc-cache': ICON_NAMES.fileText,
  'app.jetbrains-cache': ICON_NAMES.brandJetbrains,
  'app.maven-cache': ICON_NAMES.brandApacheMaven,
  'app.minecraft-cache': ICON_NAMES.brandMinecraft,
  'app.npm-cache': ICON_NAMES.brandNpm,
  'app.pip-cache': ICON_NAMES.brandPython,
  'app.spotify-cache': ICON_NAMES.brandSpotify,
  'app.vscode-cache': ICON_NAMES.brandVscode,
  'app.wine-prefix-cache': ICON_NAMES.brandWine,
  'app.yarn-cache': ICON_NAMES.brandYarn,

  'browser.chrome-cache': ICON_NAMES.brandChrome,
  'browser.chrome-offline-cache': ICON_NAMES.brandChrome,
  'browser.uc-cache': ICON_NAMES.brandUcBrowser,
  'browser.360-speed-cache': ICON_NAMES.brand360Browser,
  'browser.sogou-cache': ICON_NAMES.brandSogou,
  'browser.360-safe-cache': ICON_NAMES.brand360Browser,
  'browser.2345-cache': ICON_NAMES.brand360Browser,
  'browser.edge-cache': ICON_NAMES.brandEdge,
  'browser.edge-offline-cache': ICON_NAMES.brandEdge,
  'browser.arc-cache': ICON_NAMES.brandArc,
  'browser.vivaldi-cache': ICON_NAMES.brandVivaldi,
  'browser.firefox-cache': ICON_NAMES.brandFirefox,
  'browser.opera-cache': ICON_NAMES.brandOpera,
  'browser.brave-cache': ICON_NAMES.brandBrave,
  'browser.brave-origin-cache': ICON_NAMES.brandBrave,
  'browser.chromium-cache': ICON_NAMES.brandChrome,
  'browser.duckduckgo-cache': ICON_NAMES.brandDuckDuckGo,
  'browser.gecko-family-cache': ICON_NAMES.cleanupBrowserData,

  'dev.browser-automation-cache': ICON_NAMES.cleanupAutomationCache,
  'dev.build-accelerator-cache': ICON_NAMES.code,
  'dev.bun-cache': ICON_NAMES.brandBun,
  'dev.ccache-cache': ICON_NAMES.code,
  'dev.cocoapods-cache': ICON_NAMES.brandCocoaPods,
  'dev.composer-cache': ICON_NAMES.brandComposer,
  'dev.editor-cache': ICON_NAMES.code,
  'dev.hex-cache': ICON_NAMES.package,
  'dev.jvm-tooling-cache': ICON_NAMES.cleanupDeveloperTools,
  'dev.maven-cache': ICON_NAMES.brandApacheMaven,
  'dev.mise-cache': ICON_NAMES.cleanupDeveloperTools,
  'dev.npm-cache': ICON_NAMES.brandNpm,
  'dev.npx-cache': ICON_NAMES.brandNpm,
  'dev.node-gyp-cache': ICON_NAMES.brandNodejs,
  'dev.node-tooling-cache': ICON_NAMES.brandNodejs,
  'dev.pnpm-cache': ICON_NAMES.brandPnpm,
  'dev.yarn-cache': ICON_NAMES.brandYarn,
  'dev.pip-cache': ICON_NAMES.brandPython,
  'dev.python-cache': ICON_NAMES.brandPython,
  'dev.python-tooling-cache': ICON_NAMES.brandPython,
  'dev.uv-cache': ICON_NAMES.brandUv,
  'dev.dart-analysis-cache': ICON_NAMES.brandDart,
  'dev.cargo-cache': ICON_NAMES.brandRust,
  'dev.cargo-extracted-sources': ICON_NAMES.brandRust,
  'dev.qclaw-compile-cache': ICON_NAMES.brandNodejs,
  'dev.go-cache': ICON_NAMES.brandGo,
  'dev.go-module-cache': ICON_NAMES.brandGo,
  'dev.swiftpm-cache': ICON_NAMES.brandSwift,
  'dev.vscode-cache': ICON_NAMES.brandVscode,
  'dev.visual-studio-cache': ICON_NAMES.brandVisualStudio,
  'dev.android-cache': ICON_NAMES.brandAndroid,
  'dev.android-user-cache': ICON_NAMES.brandAndroid,
  'dev.deno-cache': ICON_NAMES.brandDeno,
  'dev.copilot-cli-cache': ICON_NAMES.brandGithubCopilot,
  'dev.jetbrains-cache': ICON_NAMES.brandJetbrains,
  'dev.gradle-cache': ICON_NAMES.brandGradle,
  'dev.homebrew-cache': ICON_NAMES.brandHomebrew,
  'dev.nuget-cache': ICON_NAMES.brandNuget,
  'dev.package-manager-cache': ICON_NAMES.package,
  'dev.rubygems-cache': ICON_NAMES.brandRubyGems,
  'dev.sccache-cache': ICON_NAMES.code,
  'dev.user-tool-cache': ICON_NAMES.cleanupDeveloperTools,
  'dev.pyinstaller-cache': ICON_NAMES.brandPython,
  'dev.qoder-rendering-cache': ICON_NAMES.code,

  'dev.xcode-derived-data': ICON_NAMES.brandXcode,
  'dev.xcode-auxiliary-cache': ICON_NAMES.brandXcode,
  'dev.xcode-simulator-cache': ICON_NAMES.brandXcode,
  'special.xcode-device-support': ICON_NAMES.brandXcode,
  'special.xcode-simulator-runtime': ICON_NAMES.brandXcode,
  'special.xcode-archives': ICON_NAMES.brandXcode,

  'special.ai-model-openai-clip': ICON_NAMES.brandOpenai,
  'ai.claude-code-cache': ICON_NAMES.brandClaudeCode,
  'special.ai-model-whisper': ICON_NAMES.fileAudio,
  'special.ai-model-pytorch': ICON_NAMES.brandPyTorch,
  'special.ai-cache-pytorch-hub-repositories': ICON_NAMES.brandPyTorch,
  'special.ai-model-keras': ICON_NAMES.brandKeras,
  'special.ai-model-tensorflow-hub': ICON_NAMES.brandTensorFlow,
  'special.ai-model-lm-studio': ICON_NAMES.brandLmStudio,
  'special.ai-model-coqui-tts': ICON_NAMES.fileAudio,
  'special.ai-model-gpt4all': ICON_NAMES.aiModel,
  'special.ai-model-jan': ICON_NAMES.aiModel,
  'ai.huggingface-xet-cache': ICON_NAMES.brandHuggingface,
  'special.ai-model-hugging-face': ICON_NAMES.brandHuggingface,
  'special.ai-model-ollama': ICON_NAMES.brandOllama,
  [CLEANUP_RULE_IDS.aiModelModelScope]: ICON_NAMES.brandModelScope,
  'special.codex-archived-sessions': ICON_NAMES.brandOpenai,
  'app.codex-diagnostic-cache': ICON_NAMES.brandOpenai,
  'special.rust-toolchains': ICON_NAMES.brandRust,
  'special.dropbox-cache': ICON_NAMES.brandDropbox,
  'special.iqiyi-offline-videos': ICON_NAMES.brandIqiyi,
  'special.iqiyi-playback-cache': ICON_NAMES.brandIqiyi,
  'special.qqlive-offline-videos': ICON_NAMES.brandTencentVideo,
  'special.qqlive-playback-cache': ICON_NAMES.brandTencentVideo,
  'special.youku-offline-videos': ICON_NAMES.brandYouku,
  'special.youku-playback-cache': ICON_NAMES.brandYouku,
  'special.additional-user-caches': ICON_NAMES.cleanupUserCache,
  'special.conda-cache': ICON_NAMES.brandAnaconda,

  'project.rust-build-artifacts': ICON_NAMES.brandRust,
  'project.node-build-artifacts': ICON_NAMES.brandNodejs,
  'project.react-native-build-artifacts': ICON_NAMES.brandReactNative,
  'project.python-build-artifacts': ICON_NAMES.brandPython,
  'project.dotnet-build-artifacts': ICON_NAMES.brandCSharp,
  'project.swift-build-artifacts': ICON_NAMES.brandSwift,
  'project.flutter-build-artifacts': ICON_NAMES.brandFlutter,
  'project.terraform-build-artifacts': ICON_NAMES.brandTerraform,
  'project.unity-build-artifacts': ICON_NAMES.brandUnity,
  'project.gradle-build-artifacts': ICON_NAMES.brandGradle,
  'project.godot-build-artifacts': ICON_NAMES.brandGodot,
  'project.cmake-build-artifacts': ICON_NAMES.brandCmake,
  'project.maven-build-artifacts': ICON_NAMES.brandApacheMaven,
  'project.sbt-build-artifacts': ICON_NAMES.package,
  'project.zig-build-artifacts': ICON_NAMES.brandZig,
  'project.elixir-build-artifacts': ICON_NAMES.brandElixir,
  'project.unreal-build-artifacts': ICON_NAMES.brandUnrealEngine,
  'project.cocoapods-build-artifacts': ICON_NAMES.brandCocoaPods,
  'project.haskell-build-artifacts': ICON_NAMES.brandHaskell,
  'project.composer-build-artifacts': ICON_NAMES.brandComposer,
  'project.jupyter-build-artifacts': ICON_NAMES.brandJupyter,
  'project.pixi-build-artifacts': ICON_NAMES.package,
  'project.autoconf-cache': ICON_NAMES.code,
  'project.clojure-cli-cache': ICON_NAMES.brandClojure,
  'project.dune-build-artifacts': ICON_NAMES.package,
  'project.leiningen-build-artifacts': ICON_NAMES.brandClojure,
  'project.meson-build-artifacts': ICON_NAMES.package,
  'project.mill-build-artifacts': ICON_NAMES.package,
  'project.pants-workdir': ICON_NAMES.package,
  'project.rails-cache': ICON_NAMES.brandRuby,
  'project.rebar-build-artifacts': ICON_NAMES.brandErlang,

  'container.docker-desktop-rendering-cache': ICON_NAMES.brandDocker,
  'container.docker-desktop-diagnostic-cache': ICON_NAMES.brandDocker,

  [CLEANUP_RULE_IDS.dockerBuildCache]: ICON_NAMES.cleanupContainerCache,
  [CLEANUP_RULE_IDS.macosUniversalBinaries]: ICON_NAMES.cleanupUniversalBinary,
};

export function cleanupGroupIcon(group: CleanupResultGroup): IconName {
  return CLEANUP_GROUP_ICONS[group];
}

export function cleanupRuleIcon(ruleId: string, group: CleanupResultGroup): IconName {
  return CLEANUP_RULE_ICONS[ruleId] ?? cleanupGroupIcon(group);
}

export function hasCleanupRuleIcon(ruleId: string): boolean {
  return Object.hasOwn(CLEANUP_RULE_ICONS, ruleId);
}
